import { randomUUID } from 'node:crypto';
import { prisma } from '@/lib/db/prisma';
import { TicketActivityType } from '@/generated/prisma';
import { attachmentConfig } from '@/lib/attachments/config';
import {
  ATTACHMENT_FALLBACK_MIME_TYPE,
  FALLBACK_ATTACHMENT_FILENAME,
  normalizeAttachmentMimeType,
  sanitizeAttachmentFilename,
} from '@/lib/attachments/filename';
import { getStorageProvider } from '@/lib/attachments/local-storage';
import type { StorageProvider } from '@/lib/attachments/storage.interface';
import { requireCustomerInWorkspace } from '@/lib/customer-portal/session';
import { CUSTOMER_ATTACHMENTS_PER_MESSAGE_LIMIT } from '@/lib/customer-portal/schema';
import {
  CustomerAttachmentNotFoundError,
  CustomerAttachmentValidationError,
  CustomerAttachmentStorageError,
} from '@/lib/customer-portal/errors';
import type { CustomerAttachmentView } from '@/lib/customer-portal/dto';
import type { MessageAuthorType } from '@/lib/messages/authorship';
import type { Prisma } from '@/generated/prisma';

/**
 * Customer attachment service (Phase 9 Task 4).
 *
 * This module is deliberately a *sibling* of `src/lib/attachments/service.ts`,
 * not an extension of it. The internal service opens with
 * `getCurrentMembership()` — a Better Auth workspace session, which a customer
 * session can never satisfy. Adding a customer branch to that path would have
 * meant a single function answering "authorized?" for two different principal
 * types, and the branch would be decided by the shape of the request. Here the
 * two authorization domains share no call path at all: this file imports
 * `requireCustomerInWorkspace` and never `getCurrentMembership`, so a customer
 * endpoint has no reachable route to membership-based authorization.
 *
 * Storage is the one thing that *is* shared, and deliberately: the
 * `StorageProvider` is a storage abstraction, not an authorization one. Both
 * services write through it under an opaque UUID key.
 *
 * The authorization chain, in full:
 *
 * ```text
 * customer session
 *   -> workspace + customerId resolved server-side
 *   -> ticket WHERE id = ? AND workspaceId = ? AND customerId = ?
 *   -> message WHERE id = ? AND ticketId = ? AND authorType = 'customer'
 *                        AND customerId = ? AND createdById IS NULL
 *   -> attachment WHERE message -> ticket -> (workspaceId, customerId)
 * ```
 *
 * Every ownership predicate is a `where` clause, not a post-fetch comparison.
 * That is not stylistic: it means a foreign id matches zero rows and raises the
 * same error as a nonexistent one, so there is no code path in which a row is
 * read and then judged — and no code path where a forgotten comparison would
 * become a cross-customer leak.
 *
 * `storageKey` never leaves this module. It is selected only inside the
 * authorization predicate's query and returned only to the storage provider.
 */

export {
  CustomerAttachmentNotFoundError,
  CustomerAttachmentValidationError,
  CustomerAttachmentStorageError,
};

export type CustomerAttachmentDownload = {
  buffer: Buffer;
  /** Already sanitized; safe to place in a header or render. */
  filename: string;
  mimeType: string;
  sizeBytes: number;
};

/**
 * The only value substituted for a MIME type this module cannot vouch for
 * (OMP remediation, Task 4 audit).
 *
 * The download route writes `mimeType` straight into a response header. The
 * previous `normalizeAttachmentMimeType(stored) || stored` fell back to the
 * *raw stored string* whenever normalization came back empty — so a legacy row
 * holding `text/plain\r\nX-Injected: yes` (or anything else the normalizer
 * rejects) would have been handed to `new Response()` verbatim. Whether that
 * produces a second header depends on the runtime: Node's `Headers` throws on a
 * CR/LF in a value, but that is a downstream accident, not a control, and other
 * runtimes are more permissive. The application must decide the value, not the
 * HTTP layer.
 *
 * The constant itself lives in `./filename`, so this server-only path and the
 * client-safe customer DTO cannot drift into two different fallbacks.
 */
const FALLBACK_CONTENT_TYPE = ATTACHMENT_FALLBACK_MIME_TYPE;

/**
 * Author types whose attachments a customer may see and download.
 *
 * `agent` and `customer` are the customer-visible conversation. `system` is
 * excluded deliberately: a system entry is generated by internal automation,
 * and Task 4 treats its attachments as internal-only. `internal_notes` are not
 * `Message` rows at all and so cannot be reached through this chain by
 * construction.
 */
export const CUSTOMER_VISIBLE_ATTACHMENT_AUTHOR_TYPES: readonly MessageAuthorType[] = [
  'agent',
  'customer',
];

/**
 * Opaque storage key. Deliberately contains no customer-controlled bytes, so a
 * filename can never influence where a file is written — and cannot be used to
 * traverse out of the storage root.
 */
function generateStorageKey(): string {
  return `attachments/${randomUUID()}`;
}

/**
 * Asserts the file is something the portal is willing to accept.
 *
 * Three properties, all server-derived:
 *
 *  - **non-empty** — an empty buffer is never a useful attachment and would
 *    otherwise occupy a row and a storage object forever;
 *  - **bounded size** — measured from the received buffer, not from a declared
 *    length or a browser-side `File.size`;
 *  - **allowlisted MIME** — the allowlist is exact-match and contains no
 *    wildcards, so a bare `image`/`png` wildcard, `application/x-executable`
 *    and `application/javascript` are all rejected regardless of what the file
 *    is called.
 *
 * A fourth property, a bounded per-message count so one message cannot be used
 * to accumulate unbounded storage, is enforced separately and not here: it is a
 * statement about the database, not about these bytes, and it must be read under
 * the same lock that guards the insert. See {@link assertAttachmentCapacityUnderLock}.
 *
 * Returns the values to persist, so the caller cannot accidentally write the
 * un-normalized inputs alongside the checked ones.
 */
function validateCustomerAttachment(input: {
  buffer: Buffer;
  declaredMimeType: string | null | undefined;
  declaredFilename: string | null | undefined;
}): { filename: string; mimeType: string; sizeBytes: number } {
  if (input.buffer.length === 0) {
    throw new CustomerAttachmentValidationError('The file is empty.');
  }

  if (input.buffer.length > attachmentConfig.maxFileSizeBytes) {
    throw new CustomerAttachmentValidationError(
      `The file is larger than the ${Math.floor(attachmentConfig.maxFileSizeBytes / (1024 * 1024))} MB limit.`,
    );
  }

  // The count cap is deliberately NOT checked here. It moved into the metadata
  // transaction, under a row lock on the message — see the comment above
  // `lockMessageForCustomerAttachment`. These three checks are pure functions of
  // the request bytes, so they stay outside the transaction and outside the lock.

  const mimeType = normalizeAttachmentMimeType(input.declaredMimeType);

  if (!isAllowedCustomerAttachmentMimeType(mimeType)) {
    throw new CustomerAttachmentValidationError('That file type is not supported.');
  }

  const filename = sanitizeAttachmentFilename(input.declaredFilename);

  return {
    filename,
    mimeType,
    // Derived from the bytes actually received. Never from a form field, a
    // header, or the declared length.
    sizeBytes: input.buffer.length,
  };
}

/** Exact-match check against the existing allowlist; no wildcards, no prefixes. */
function isAllowedCustomerAttachmentMimeType(mimeType: string): boolean {
  return (attachmentConfig.allowedMimeTypes as readonly string[]).includes(mimeType);
}

export type UploadCustomerAttachmentInput = {
  workspaceSlug: string;
  ticketId: string;
  messageId: string;
  declaredFilename: string | null | undefined;
  declaredMimeType: string | null | undefined;
  buffer: Buffer;
};

/**
 * Attaches a file to a customer-authored message on a ticket the customer owns.
 *
 * The authorization query is the whole point of this function. `messageId`,
 * `ticketId` and `workspaceSlug` are all caller-supplied *lookup keys*; none of
 * them decides who the caller is, and none of them can widen the result, because
 * the query additionally requires the ticket to belong to the session's
 * `(workspaceId, customerId)` pair and the message to belong to that ticket.
 *
 * The four authorship conditions together are what makes "customer-authored"
 * true rather than inferred:
 *
 * ```text
 * message.authorType = 'customer'
 * message.customerId  = session customer
 * message.createdById IS NULL
 * message.ticketId    = requested ticket
 * ```
 *
 * An agent message, a system message and a message authored by another customer
 * all fail at least one, and therefore match zero rows. So does a message on a
 * ticket the customer does not own, and a message in another workspace — which
 * is why all of them raise the same
 * {@link CustomerAttachmentNotFoundError} rather than a distinct "forbidden".
 *
 * Storage ordering follows the internal service, and for the same reason: the
 * provider has no transaction to enlist in, so the file lands first and the
 * metadata second. If the metadata transaction fails, the stored object is
 * deleted before the error propagates — a customer never ends up paying for a
 * file the database does not know about. A cleanup failure is logged server-side
 * and does not replace the original error.
 *
 * Returns a customer-safe DTO: no `storageKey`, no `messageId`, no `customerId`,
 * no ticket metadata.
 */
export async function uploadCustomerAttachment(
  input: UploadCustomerAttachmentInput,
  storage: StorageProvider = getStorageProvider(),
): Promise<CustomerAttachmentView> {
  const { workspace, customer } = await requireCustomerInWorkspace(input.workspaceSlug);

  const message = await findOwnedCustomerMessage(input.messageId, input.ticketId, {
    workspaceId: workspace.id,
    customerId: customer.customerId,
  });

  if (!message) {
    throw new CustomerAttachmentNotFoundError();
  }

  // Byte-level checks only. No count here: the capacity check must not run before
  // the lock, or it is worthless (see the upload function's doc comment).
  const validated = validateCustomerAttachment({
    buffer: input.buffer,
    declaredMimeType: input.declaredMimeType,
    declaredFilename: input.declaredFilename,
  });

  const storageKey = generateStorageKey();

  try {
    await storage.put(storageKey, input.buffer);
  } catch (error) {
    // The cause is logged rather than swallowed, because "storage rejected the
    // write" is the difference between a disk problem and a full volume — and
    // nothing about it is customer-facing. The thrown message is a fixed
    // literal: it names no path, no key and no underlying error, because the
    // route maps this class to a generic `500`.
    console.error('[customer-attachments] storage write failed:', error);

    throw new CustomerAttachmentStorageError('The file could not be stored.');
  }

  let created: { id: string; originalFilename: string; mimeType: string; sizeBytes: number; createdAt: Date };

  try {
    created = await prisma.$transaction(async (tx) => {
      // Lock, then count, then insert. All three in one transaction, so the
      // count and the row it protects cannot be interleaved with a sibling.
      //
      // Serializes every concurrent upload to this one message. Taken before the
      // count and held until commit, so the count this transaction sees already
      // accounts for any sibling upload that committed first — and a sibling
      // that has not yet committed is blocked here, so it will read *our* new
      // row rather than a stale 9.
      await lockMessageForCustomerAttachment(tx, message.id);

      await assertAttachmentCapacityUnderLock(tx, message.id);

      const attachment = await tx.attachment.create({
        data: {
          messageId: message.id,
          originalFilename: validated.filename,
          mimeType: validated.mimeType,
          sizeBytes: validated.sizeBytes,
          storageKey,
        },
        select: {
          id: true,
          originalFilename: true,
          mimeType: true,
          sizeBytes: true,
          createdAt: true,
        },
      });

      // Internal activity only. `actorId` is null because a customer is not a
      // `User`: attributing the upload to an arbitrary workspace user would
      // fabricate an actor. The ticket comes from the authorized message, never
      // from the request.
      await tx.ticketActivity.create({
        data: {
          ticketId: message.ticketId,
          actorId: null,
          type: TicketActivityType.ATTACHMENT_ADDED,
          metadata: { attachmentId: attachment.id, filename: validated.filename },
        },
      });

      return attachment;
    });
  } catch (error) {
    // The provider wrote the file first and cannot enlist in the transaction,
    // so the object is now orphaned and must be removed before the failure
    // propagates. Logged, never surfaced: a surviving orphan is an operational
    // fact, not something a customer can act on.
    console.error('[customer-attachments] attachment metadata write failed:', error);

    await cleanupStoredObject(storage, storageKey);

    // Two outcomes of this transaction are not infrastructure faults and must
    // keep their own class and status rather than being flattened into the
    // generic 500 below:
    //
    //  - **capacity** — a full message is the business rule working as intended;
    //  - **vanished message** — the row resolved moments ago was deleted before
    //    the lock was taken, so there is genuinely nothing to attach to. This one
    //    only became reachable when the lock was added, which is exactly why it
    //    is called out: without this, deleting a message mid-upload would
    //    surface as a 500 rather than the 404 the same request already produces
    //    when the row is gone before the transaction.
    if (
      error instanceof CustomerAttachmentValidationError ||
      error instanceof CustomerAttachmentNotFoundError
    ) {
      throw error;
    }

    // Re-thrown as a portal-safe error: a Prisma failure carries SQL, constraint
    // names and parameter values, none of which may reach a customer.
    throw new CustomerAttachmentStorageError('The attachment could not be recorded.');
  }

  return {
    id: created.id,
    originalFilename: created.originalFilename,
    mimeType: created.mimeType,
    sizeBytes: created.sizeBytes,
    createdAt: created.createdAt.toISOString(),
  };
}

/**
 * Reads an attachment the customer is entitled to download.
 *
 * The predicate walks the whole chain in one query — `attachment -> message ->
 * ticket -> (workspaceId, customerId)` — plus the customer-visible author-type
 * restriction. There is no intermediate read whose result could be forgotten
 * before the check, and no ordering in which a row is loaded and then judged.
 *
 * An attachment on another customer's message, in another workspace, or on a
 * system message matches zero rows and is indistinguishable from one that does
 * not exist. An attachment id alone is therefore never sufficient.
 *
 * Sanitizing on the way out as well as on the way in means an attachment stored
 * before this task existed — by the internal route, which does not sanitize — is
 * still safe to render and to put in a header.
 */
export async function downloadCustomerAttachment(
  input: { workspaceSlug: string; attachmentId: string },
  storage: StorageProvider = getStorageProvider(),
): Promise<CustomerAttachmentDownload> {
  const { workspace, customer } = await requireCustomerInWorkspace(input.workspaceSlug);

  const attachment = await prisma.attachment.findFirst({
    where: {
      id: input.attachmentId,
      message: {
        authorType: { in: [...CUSTOMER_VISIBLE_ATTACHMENT_AUTHOR_TYPES] },
        ticket: {
          workspaceId: workspace.id,
          customerId: customer.customerId,
        },
      },
    },
    select: {
      id: true,
      storageKey: true,
      originalFilename: true,
      mimeType: true,
      sizeBytes: true,
    },
  });

  if (!attachment) {
    throw new CustomerAttachmentNotFoundError();
  }

  let buffer: Buffer;

  try {
    buffer = await storage.get(attachment.storageKey);
  } catch {
    // A metadata row with no stored object is an internal inconsistency, not a
    // customer error and not a "not found" — answering 404 would imply the
    // attachment does not exist, which is a different (and false) statement.
    throw new CustomerAttachmentStorageError('The file could not be read.');
  }

  return {
    buffer,
    filename: sanitizeAttachmentFilename(attachment.originalFilename),
    // Fail closed. Never the raw stored value: this string becomes a response
    // header, and a legacy row may hold anything an agent's browser sent. If
    // normalization cannot vouch for the value, the customer gets a neutral
    // type rather than an attacker-influenced one.
    mimeType: normalizeAttachmentMimeType(attachment.mimeType) || FALLBACK_CONTENT_TYPE,
    sizeBytes: attachment.sizeBytes,
  };
}

type AttachmentLockClient = Pick<Prisma.TransactionClient, '$queryRaw' | 'attachment'>;

/**
 * Serializes customer attachment uploads for one message.
 *
 * Why a row lock rather than an advisory lock: the `Message` row already exists
 * and is already the natural unit of work for an attachment, so this introduces
 * no second locking vocabulary — the same reasoning, and the same
 * `SELECT ... FOR UPDATE` shape, as `lockCustomerForMagicLinkIssuance` in
 * `lib/customer-access/provisioning.ts`. The lock is released at commit or
 * rollback, so it cannot leak across pooled connections.
 *
 * Why lock at all: the capacity check and the insert must be one atomic step.
 * Previously the count was read *before* the transaction, so two concurrent
 * uploads to a message holding 9 attachments both read `9`, both saw room, and
 * both inserted — leaving 11 attachments on a message whose documented limit is
 * 10. A count is only meaningful if it is read while every other inserter for
 * that message is excluded.
 *
 * Why this is not a global lock: the scope is one `Message` row, keyed by the id
 * the caller already resolved through {@link findOwnedCustomerMessage}. Uploads
 * to different messages never contend. An advisory lock keyed the same way would
 * also serialize, but it is anonymous in `pg_locks` and outlives the row it
 * describes; the message row is the durable, self-describing lock.
 *
 * The id is interpolated as a bound parameter, never concatenated, and this
 * function accepts no broader scope (a ticket, a workspace, or "any message") —
 * the lock is always exactly the one already-authorized message.
 *
 * Lock order is uniform (this message row only, then attachment inserts against
 * it), so no deadlock cycle can form between concurrent uploads.
 */
async function lockMessageForCustomerAttachment(
  tx: AttachmentLockClient,
  messageId: string,
): Promise<void> {
  const locked = await tx.$queryRaw<{ id: string }[]>`
    SELECT "id" FROM "Message" WHERE "id" = ${messageId}
    FOR UPDATE
  `;

  // The row was resolved moments ago in this same request, so its absence means
  // it was deleted in between. Nothing to attach to, and nothing to count.
  if (locked.length !== 1 || locked[0]!.id !== messageId) {
    throw new CustomerAttachmentNotFoundError();
  }
}

/**
 * Enforces the per-message attachment cap *while the message row is locked*.
 *
 * Splitting this out from {@link validateCustomerAttachment} is the point of the
 * fix: it is a query against live database state, so it has to run inside the
 * transaction that holds the lock and immediately before the insert it protects.
 * A count taken outside the lock, or before a sibling writer acquired the lock,
 * is a read of a stale snapshot.
 *
 * The comparison is `>=`, so reaching the limit is permitted and exceeding it is
 * not — the same semantics the previous pre-transaction check used.
 *
 * Must be called inside the same transaction as {@link lockMessageForCustomerAttachment}
 * and the attachment insert; committing in between would release the lock and
 * reopen the race.
 */
async function assertAttachmentCapacityUnderLock(
  tx: AttachmentLockClient,
  messageId: string,
): Promise<void> {
  const count = await tx.attachment.count({ where: { messageId } });

  if (count >= CUSTOMER_ATTACHMENTS_PER_MESSAGE_LIMIT) {
    throw new CustomerAttachmentValidationError(
      `A message can have at most ${CUSTOMER_ATTACHMENTS_PER_MESSAGE_LIMIT} attachments.`,
    );
  }
}

/**
 * The single authorization query for upload.
 *
 * Every condition is a `where` clause. The `message` object is returned only
 * because its `ticketId` is needed for the activity row; nothing authorizes
 * after the fact.
 */
function findOwnedCustomerMessage(
  messageId: string,
  ticketId: string,
  owner: { workspaceId: string; customerId: string },
): Promise<{ id: string; ticketId: string } | null> {
  return prisma.message.findFirst({
    where: {
      id: messageId,
      ticketId,
      authorType: 'customer',
      customerId: owner.customerId,
      createdById: null,
      ticket: {
        workspaceId: owner.workspaceId,
        customerId: owner.customerId,
      },
    },
    select: { id: true, ticketId: true },
  });
}

/**
 * Best-effort removal of a stored object whose metadata was never written.
 *
 * A cleanup failure is logged and swallowed: the caller is already failing with
 * a real error, and replacing that with "cleanup failed" would hide the cause.
 * The log records the key, which is server-side only — the storage root is not
 * under `public/`, and the key is never returned to a customer.
 */
async function cleanupStoredObject(storage: StorageProvider, storageKey: string): Promise<void> {
  try {
    if (await storage.exists(storageKey)) {
      await storage.delete(storageKey);
    }
  } catch (error) {
    console.error(`[customer-attachments] storage cleanup failed for key ${storageKey}:`, error);
  }
}

export { FALLBACK_ATTACHMENT_FILENAME };