import { randomUUID } from 'node:crypto';
import { prisma } from '@/lib/db/prisma';
import { TicketActivityType } from '@/generated/prisma';
import { attachmentConfig } from '@/lib/attachments/config';
import {
  FALLBACK_ATTACHMENT_FILENAME,
  normalizeAttachmentMimeType,
  sanitizeAttachmentFilename,
} from '@/lib/attachments/filename';
import { getStorageProvider } from '@/lib/attachments/local-storage';
import type { StorageProvider } from '@/lib/attachments/storage.interface';
import { requireCustomerInWorkspace } from '@/lib/customer-portal/session';
import { CUSTOMER_ATTACHMENTS_PER_MESSAGE_LIMIT } from '@/lib/customer-portal/schema';
import {
  CustomerAttachmentNotFoundError,
  CustomerAttachmentValidationError,
  CustomerAttachmentStorageError,
} from '@/lib/customer-portal/errors';
import type { CustomerAttachmentView } from '@/lib/customer-portal/dto';
import type { MessageAuthorType } from '@/lib/messages/authorship';

/**
 * Customer attachment service (Phase 9 Task 4).
 *
 * This module is deliberately a *sibling* of `src/lib/attachments/service.ts`,
 * not an extension of it. The internal service opens with
 * `getCurrentMembership()` — a Better Auth workspace session, which a customer
 * session can never satisfy. Adding a customer branch to that path would have
 * meant a single function answering "authorized?" for two different principal
 * types, and the branch would be decided by the shape of the request. Here the
 * two authorization domains share no call path at all: this file imports
 * `requireCustomerInWorkspace` and never `getCurrentMembership`, so a customer
 * endpoint has no reachable route to membership-based authorization.
 *
 * Storage is the one thing that *is* shared, and deliberately: the
 * `StorageProvider` is a storage abstraction, not an authorization one. Both
 * services write through it under an opaque UUID key.
 *
 * The authorization chain, in full:
 *
 * ```text
 * customer session
 *   -> workspace + customerId resolved server-side
 *   -> ticket WHERE id = ? AND workspaceId = ? AND customerId = ?
 *   -> message WHERE id = ? AND ticketId = ? AND authorType = 'customer'
 *                        AND customerId = ? AND createdById IS NULL
 *   -> attachment WHERE message -> ticket -> (workspaceId, customerId)
 * ```
 *
 * Every ownership predicate is a `where` clause, not a post-fetch comparison.
 * That is not stylistic: it means a foreign id matches zero rows and raises the
 * same error as a nonexistent one, so there is no code path in which a row is
 * read and then judged — and no code path where a forgotten comparison would
 * become a cross-customer leak.
 *
 * `storageKey` never leaves this module. It is selected only inside the
 * authorization predicate's query and returned only to the storage provider.
 */

export {
  CustomerAttachmentNotFoundError,
  CustomerAttachmentValidationError,
  CustomerAttachmentStorageError,
};

export type CustomerAttachmentDownload = {
  buffer: Buffer;
  /** Already sanitized; safe to place in a header or render. */
  filename: string;
  mimeType: string;
  sizeBytes: number;
};

/**
 * Author types whose attachments a customer may see and download.
 *
 * `agent` and `customer` are the customer-visible conversation. `system` is
 * excluded deliberately: a system entry is generated by internal automation,
 * and Task 4 treats its attachments as internal-only. `internal_notes` are not
 * `Message` rows at all and so cannot be reached through this chain by
 * construction.
 */
export const CUSTOMER_VISIBLE_ATTACHMENT_AUTHOR_TYPES: readonly MessageAuthorType[] = [
  'agent',
  'customer',
];

/**
 * Opaque storage key. Deliberately contains no customer-controlled bytes, so a
 * filename can never influence where a file is written — and cannot be used to
 * traverse out of the storage root.
 */
function generateStorageKey(): string {
  return `attachments/${randomUUID()}`;
}

/**
 * Asserts the file is something the portal is willing to accept.
 *
 * Four properties, all server-derived:
 *
 *  - **non-empty** — an empty buffer is never a useful attachment and would
 *    otherwise occupy a row and a storage object forever;
 *  - **bounded size** — measured from the received buffer, not from a declared
 *    length or a browser-side `File.size`;
 *  - **allowlisted MIME** — the allowlist is exact-match and contains no
 *    wildcards, so a bare `image`/`png` wildcard, `application/x-executable`
 *    and `application/javascript` are all rejected regardless of what the file
 *    is called;
 *  - **documented count** — bounded per message so one message cannot be used to
 *    accumulate unbounded storage.
 *
 * Returns the values to persist, so the caller cannot accidentally write the
 * un-normalized inputs alongside the checked ones.
 */
function validateCustomerAttachment(input: {
  buffer: Buffer;
  declaredMimeType: string | null | undefined;
  declaredFilename: string | null | undefined;
  currentAttachmentCount: number;
}): { filename: string; mimeType: string; sizeBytes: number } {
  if (input.buffer.length === 0) {
    throw new CustomerAttachmentValidationError('The file is empty.');
  }

  if (input.buffer.length > attachmentConfig.maxFileSizeBytes) {
    throw new CustomerAttachmentValidationError(
      `The file is larger than the ${Math.floor(attachmentConfig.maxFileSizeBytes / (1024 * 1024))} MB limit.`,
    );
  }

  if (input.currentAttachmentCount >= CUSTOMER_ATTACHMENTS_PER_MESSAGE_LIMIT) {
    throw new CustomerAttachmentValidationError(
      `A message can have at most ${CUSTOMER_ATTACHMENTS_PER_MESSAGE_LIMIT} attachments.`,
    );
  }

  const mimeType = normalizeAttachmentMimeType(input.declaredMimeType);

  if (!isAllowedCustomerAttachmentMimeType(mimeType)) {
    throw new CustomerAttachmentValidationError('That file type is not supported.');
  }

  const filename = sanitizeAttachmentFilename(input.declaredFilename);

  return {
    filename,
    mimeType,
    // Derived from the bytes actually received. Never from a form field, a
    // header, or the declared length.
    sizeBytes: input.buffer.length,
  };
}

/** Exact-match check against the existing allowlist; no wildcards, no prefixes. */
function isAllowedCustomerAttachmentMimeType(mimeType: string): boolean {
  return (attachmentConfig.allowedMimeTypes as readonly string[]).includes(mimeType);
}

export type UploadCustomerAttachmentInput = {
  workspaceSlug: string;
  ticketId: string;
  messageId: string;
  declaredFilename: string | null | undefined;
  declaredMimeType: string | null | undefined;
  buffer: Buffer;
};

/**
 * Attaches a file to a customer-authored message on a ticket the customer owns.
 *
 * The authorization query is the whole point of this function. `messageId`,
 * `ticketId` and `workspaceSlug` are all caller-supplied *lookup keys*; none of
 * them decides who the caller is, and none of them can widen the result, because
 * the query additionally requires the ticket to belong to the session's
 * `(workspaceId, customerId)` pair and the message to belong to that ticket.
 *
 * The four authorship conditions together are what makes "customer-authored"
 * true rather than inferred:
 *
 * ```text
 * message.authorType = 'customer'
 * message.customerId  = session customer
 * message.createdById IS NULL
 * message.ticketId    = requested ticket
 * ```
 *
 * An agent message, a system message and a message authored by another customer
 * all fail at least one, and therefore match zero rows. So does a message on a
 * ticket the customer does not own, and a message in another workspace — which
 * is why all of them raise the same
 * {@link CustomerAttachmentNotFoundError} rather than a distinct "forbidden".
 *
 * Storage ordering follows the internal service, and for the same reason: the
 * provider has no transaction to enlist in, so the file lands first and the
 * metadata second. If the metadata transaction fails, the stored object is
 * deleted before the error propagates — a customer never ends up paying for a
 * file the database does not know about. A cleanup failure is logged server-side
 * and does not replace the original error.
 *
 * Returns a customer-safe DTO: no `storageKey`, no `messageId`, no `customerId`,
 * no ticket metadata.
 */
export async function uploadCustomerAttachment(
  input: UploadCustomerAttachmentInput,
  storage: StorageProvider = getStorageProvider(),
): Promise<CustomerAttachmentView> {
  const { workspace, customer } = await requireCustomerInWorkspace(input.workspaceSlug);

  const message = await findOwnedCustomerMessage(input.messageId, input.ticketId, {
    workspaceId: workspace.id,
    customerId: customer.customerId,
  });

  if (!message) {
    throw new CustomerAttachmentNotFoundError();
  }

  const currentAttachmentCount = await prisma.attachment.count({
    where: { messageId: message.id },
  });

  const validated = validateCustomerAttachment({
    buffer: input.buffer,
    declaredMimeType: input.declaredMimeType,
    declaredFilename: input.declaredFilename,
    currentAttachmentCount,
  });

  const storageKey = generateStorageKey();

  try {
    await storage.put(storageKey, input.buffer);
  } catch (error) {
    // The cause is logged rather than swallowed, because "storage rejected the
    // write" is the difference between a disk problem and a full volume — and
    // nothing about it is customer-facing. The thrown message is a fixed
    // literal: it names no path, no key and no underlying error, because the
    // route maps this class to a generic `500`.
    console.error('[customer-attachments] storage write failed:', error);

    throw new CustomerAttachmentStorageError('The file could not be stored.');
  }

  let created: { id: string; originalFilename: string; mimeType: string; sizeBytes: number; createdAt: Date };

  try {
    created = await prisma.$transaction(async (tx) => {
      const attachment = await tx.attachment.create({
        data: {
          messageId: message.id,
          originalFilename: validated.filename,
          mimeType: validated.mimeType,
          sizeBytes: validated.sizeBytes,
          storageKey,
        },
        select: {
          id: true,
          originalFilename: true,
          mimeType: true,
          sizeBytes: true,
          createdAt: true,
        },
      });

      // Internal activity only. `actorId` is null because a customer is not a
      // `User`: attributing the upload to an arbitrary workspace user would
      // fabricate an actor. The ticket comes from the authorized message, never
      // from the request.
      await tx.ticketActivity.create({
        data: {
          ticketId: message.ticketId,
          actorId: null,
          type: TicketActivityType.ATTACHMENT_ADDED,
          metadata: { attachmentId: attachment.id, filename: validated.filename },
        },
      });

      return attachment;
    });
  } catch (error) {
    // The provider wrote the file first and cannot enlist in the transaction,
    // so the object is now orphaned and must be removed before the failure
    // propagates. Logged, never surfaced: a surviving orphan is an operational
    // fact, not something a customer can act on.
    console.error('[customer-attachments] attachment metadata write failed:', error);

    await cleanupStoredObject(storage, storageKey);

    // Re-thrown as a portal-safe error: a Prisma failure carries SQL, constraint
    // names and parameter values, none of which may reach a customer.
    throw new CustomerAttachmentStorageError('The attachment could not be recorded.');
  }

  return {
    id: created.id,
    originalFilename: created.originalFilename,
    mimeType: created.mimeType,
    sizeBytes: created.sizeBytes,
    createdAt: created.createdAt.toISOString(),
  };
}

/**
 * Reads an attachment the customer is entitled to download.
 *
 * The predicate walks the whole chain in one query — `attachment -> message ->
 * ticket -> (workspaceId, customerId)` — plus the customer-visible author-type
 * restriction. There is no intermediate read whose result could be forgotten
 * before the check, and no ordering in which a row is loaded and then judged.
 *
 * An attachment on another customer's message, in another workspace, or on a
 * system message matches zero rows and is indistinguishable from one that does
 * not exist. An attachment id alone is therefore never sufficient.
 *
 * Sanitizing on the way out as well as on the way in means an attachment stored
 * before this task existed — by the internal route, which does not sanitize — is
 * still safe to render and to put in a header.
 */
export async function downloadCustomerAttachment(
  input: { workspaceSlug: string; attachmentId: string },
  storage: StorageProvider = getStorageProvider(),
): Promise<CustomerAttachmentDownload> {
  const { workspace, customer } = await requireCustomerInWorkspace(input.workspaceSlug);

  const attachment = await prisma.attachment.findFirst({
    where: {
      id: input.attachmentId,
      message: {
        authorType: { in: [...CUSTOMER_VISIBLE_ATTACHMENT_AUTHOR_TYPES] },
        ticket: {
          workspaceId: workspace.id,
          customerId: customer.customerId,
        },
      },
    },
    select: {
      id: true,
      storageKey: true,
      originalFilename: true,
      mimeType: true,
      sizeBytes: true,
    },
  });

  if (!attachment) {
    throw new CustomerAttachmentNotFoundError();
  }

  let buffer: Buffer;

  try {
    buffer = await storage.get(attachment.storageKey);
  } catch {
    // A metadata row with no stored object is an internal inconsistency, not a
    // customer error and not a "not found" — answering 404 would imply the
    // attachment does not exist, which is a different (and false) statement.
    throw new CustomerAttachmentStorageError('The file could not be read.');
  }

  return {
    buffer,
    filename: sanitizeAttachmentFilename(attachment.originalFilename),
    // Normalized again before it becomes a response header. Both upload paths
    // already stored a normalized, allowlisted value, so this is belt-and-braces
    // for rows written before either path did — a stored string with parameters
    // or odd casing must not reach `Content-Type` unexamined.
    mimeType: normalizeAttachmentMimeType(attachment.mimeType) || attachment.mimeType,
    sizeBytes: attachment.sizeBytes,
  };
}

/**
 * The single authorization query for upload.
 *
 * Every condition is a `where` clause. The `message` object is returned only
 * because its `ticketId` is needed for the activity row; nothing authorizes
 * after the fact.
 */
function findOwnedCustomerMessage(
  messageId: string,
  ticketId: string,
  owner: { workspaceId: string; customerId: string },
): Promise<{ id: string; ticketId: string } | null> {
  return prisma.message.findFirst({
    where: {
      id: messageId,
      ticketId,
      authorType: 'customer',
      customerId: owner.customerId,
      createdById: null,
      ticket: {
        workspaceId: owner.workspaceId,
        customerId: owner.customerId,
      },
    },
    select: { id: true, ticketId: true },
  });
}

/**
 * Best-effort removal of a stored object whose metadata was never written.
 *
 * A cleanup failure is logged and swallowed: the caller is already failing with
 * a real error, and replacing that with "cleanup failed" would hide the cause.
 * The log records the key, which is server-side only — the storage root is not
 * under `public/`, and the key is never returned to a customer.
 */
async function cleanupStoredObject(storage: StorageProvider, storageKey: string): Promise<void> {
  try {
    if (await storage.exists(storageKey)) {
      await storage.delete(storageKey);
    }
  } catch (error) {
    console.error(`[customer-attachments] storage cleanup failed for key ${storageKey}:`, error);
  }
}

export { FALLBACK_ATTACHMENT_FILENAME };